### ISSUE TITLE
Relation to non-Web Payment Scenarios?

### ISSUE THREAD

**Issue by cyberphone** [w3c/pisp-credit#2]
@CYV Few banks seem interested in putting resources on _new_ systems that only cover a fraction of typical use cases.

https://www.nfcworld.com/2017/02/14/350165/norwegian-banks-join-dnb-make-vipps-single-mobile-wallet-customers/
“Vipps has ambitions to become a 360 degrees payment service for all situations,” DNB says

How about this particular effort?

**Comment by CYV** [comment]
@cyberphone  DNB should join the W3C to contrinbute ?

**Comment by cyberphone** [comment]
@CYV Currently all mobile payment systems build on proprietary and secret technology making them poor candidates for standardization.

If there is anything to standardize, I would say that the Desktop Web to Mobile Payment Device "invocation" would be an excellent choice.  Currently these scenarios typically use mobile phone numbers or QR codes, which has no relation to `PaymentRequest`.

Due to these systems' massive popularity in for example Scandinavia, it long term leads to QR in physical shops as well which is not really that great compared to NFC.

Personally, I'm focusing on the fact that current mobile payment systems are based on the "winner-takes-it-all" strategy which has *proved* to cease working outside the country border:

![Saturn is great](https://cyberphone.github.io/doc/saturn/supervsdistrib.svg)

So there's an enormous amount of potentially useful things to do :-)

**Comment by CYV** [comment]
@cyberphone 
IMO, the face to face payment is not very interesting with current SEPA credit transfer (day+1 or more on weekend). This contexte will change with Instant credit transfer (call instant payment).

I agree that the "superprovider scenario" is country based but payment bodies in Europe are country based ... will see

**Comment by cyberphone** [comment]
@CVV Its getting hotter by the hour!
https://www.finextra.com/newsarticle/31184/danske-bank-terminates-mobilepay-in-norway-enters-talks-with-vipps

**Comment by cyberphone** [comment]
@CYV May be of some interest as well:
https://www.openbanking.org.uk/read-write-apis/payment-initiation-api/v1-1-0/#usage-examples-merchant

UK's Open Banking do not seem to target payment scenarios outside of the Web.

**Comment by cyberphone** [comment]
> I agree that the "superprovider scenario" is country based but payment bodies in Europe are country based ... will see

A question is then who is going to take on this role in France.  My guess is "nobody" because such a service would be _severely handicapped_ compared to those relying on dedicated payment interfaces  [1] rather than building on complex and still quite limited "Open Banking" APIs.

The lack of buy-in from other banks also indicate that more market research is needed.  Currently the mission looks a bit like a _"Solution Looking for a Problem"_.  iDEAL shows that other banks have already managed putting CT (Credit Transfer) on the Web in _production_ without any additions to browsers.  Yes, integration with `PaymentRequest `would indeed be cool but not at the expense of utility.

Simple question: In what way would the proposed solution provide value for _end users_ compared to for example Android Pay? AFAICT, PISP APIs introduce awkward authentication solutions making them pretty unfit outside of the Web. 


1]: BPCE seems to be supporting such a scheme as well: https://www.paylib.fr/

**Comment by ianbjacobs** [comment]
Closing this issue; please raise specific issues on the work in progress.
Ian
