### ISSUE TITLE
Unclear User/Browser Bindings

### ISSUE THREAD

**Issue by cyberphone** [w3c/pisp-credit#5]
Referring to draft 2017-10-18.

Although I haven't done a thorough analysis, I'm not entirely convinced that performing Merchant-2-PISP authentication OOB is a viable approach because it seems that the User's (actually the _browser's_) binding to the Merchant-PISP session is _missing_.  It is at least not documented.

Effectively you have (_inadvertently_) created a _potentially complex security protocol_ on top of a security scheme which in itself is non-trivial.

One may argue that the user anyway must authenticate to his/her bank but this issue is about the https://en.wikipedia.org/wiki/Ménage_à_trois which always is a bit tricky :-)

This highly related work may be worth a closer look: https://datatracker.ietf.org/wg/tokbind/about/

**Comment by cyberphone** [comment]
Since a PISP essentially is a security protocol ("firewall" between Merchant and Bank), each protocol step ought to be described in terms of security context as well.

**Comment by ianbjacobs** [comment]
Closing this as out of scope for current work.
