### ISSUE TITLE
Primitive enrollment solution

### ISSUE THREAD

**Issue by cyberphone** [w3c/pisp-credit#7]
Apparently the idea is that users should _manually_ configure payment credentials (IBAN) in a not yet defined browser UI.

The drawback with that is substantial since it excludes things like _URLs_, _Cryptographic keys_, _Logotypes_, _JSON structures_ etc.

This also departs from how other, already deployed systems work, including Apple Pay.

**Comment by ianbjacobs** [comment]
Closing this. Looking for concrete feedback on specifications. The fact that new user interface may be involved in implementing a specification is not problematic.
